// resources/js/pages/plans/Form.jsx
import { Head, Link, router, useForm } from "@inertiajs/react";
import React, { useEffect } from "react";
import { TrixEditor } from "react-trix";
import "trix/dist/trix.css"; // Pastikan CSS Trix diimpor

export default function Form({ plan }) {
    const { data, setData, errors, processing, post, progress } = useForm({
        title: plan?.title || "",
        content: plan?.content || "",
        cover: null,
        _method: plan ? "PUT" : "POST", // Untuk spoofing method di Laravel
    });

    const handleSubmit = (e) => {
        e.preventDefault();
        const url = plan
            ? route("plans.update", plan.id)
            : route("plans.store");
        // Gunakan metode 'post' dari useForm, yang secara otomatis menangani file upload.
        post(url);
    };

    const handleTrixChange = (html) => {
        setData("content", html);
    };

    // Menangani upload file di Trix Editor
    useEffect(() => {
        const handleAttachmentAdd = (event) => {
            const attachment = event.attachment;
            if (attachment.file) {
                const formData = new FormData();
                formData.append("attachment", attachment.file);

                // Kirim file ke server
                fetch(route("plans.attachments.store"), {
                    method: "POST",
                    body: formData,
                    headers: {
                        "X-CSRF-TOKEN": document.head.querySelector('meta[name="csrf-token"]').content,
                    },
                })
                .then((response) => response.json())
                .then((data) => {
                    // Beritahu Trix URL gambar yang sudah diupload
                    attachment.setAttributes({
                        url: data.url,
                        href: data.url,
                    });
                })
                .catch((error) => console.error("Upload error:", error));
            }
        };

        document.addEventListener("trix-attachment-add", handleAttachmentAdd);

        // Cleanup listener saat komponen di-unmount
        return () => {
            document.removeEventListener("trix-attachment-add", handleAttachmentAdd);
        };
    }, []);

    return (
        <div className="container mx-auto p-4 md:p-8">
            <Head title={plan ? "Ubah Rencana" : "Tambah Rencana"} />
            <div className="mb-6">
                <Link
                    href={route("plans.index")}
                    className="text-blue-600 hover:underline"
                >
                    &larr; Kembali ke Dashboard
                </Link>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                {/* Kolom Form Utama */}
                <div className="md:col-span-2 bg-white p-6 rounded-lg shadow-md">
                    <h1 className="text-2xl font-bold mb-6">
                        {plan ? "Ubah Rencana" : "Tambah Rencana Baru"}
                    </h1>
                    <form onSubmit={handleSubmit} encType="multipart/form-data">
                        {/* Judul */}
                        <div className="mb-4">
                            <label
                                htmlFor="title"
                                className="block text-sm font-medium text-gray-700"
                            >
                                Judul
                            </label>
                            <input
                                type="text"
                                id="title"
                                value={data.title}
                                onChange={(e) =>
                                    setData("title", e.target.value)
                                }
                                className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                            />
                            {errors.title && (
                                <div className="text-red-500 text-xs mt-1">
                                    {errors.title}
                                </div>
                            )}
                        </div>

                        {/* Konten (Trix Editor) */}
                        <div className="mb-6">
                            <label
                                htmlFor="content"
                                className="block text-sm font-medium text-gray-700 mb-1"
                            >
                                Konten
                            </label>
                            <TrixEditor
                                className="trix-content"
                                value={data.content}
                                onChange={handleTrixChange}
                            />
                            {errors.content && (
                                <div className="text-red-500 text-xs mt-1">
                                    {errors.content}
                                </div>
                            )}
                        </div>

                        {/* Input File untuk Cover */}
                        <div className="mb-6">
                            <label
                                htmlFor="cover"
                                className="block text-sm font-medium text-gray-700 mb-1"
                            >
                                Cover Gambar (Opsional)
                            </label>
                            <input
                                type="file"
                                id="cover"
                                onChange={(e) =>
                                    setData("cover", e.target.files[0])
                                }
                                className="w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100"
                            />
                            {errors.cover && (
                                <div className="text-red-500 text-xs mt-1">
                                    {errors.cover}
                                </div>
                            )}
                        </div>

                        {/* Progress Bar untuk Upload */}
                        {progress && (
                            <div className="w-full bg-gray-200 rounded-full mb-4">
                                <div className="bg-blue-600 text-xs font-medium text-blue-100 text-center p-0.5 leading-none rounded-full" style={{ width: `${progress.percentage}%` }}> {progress.percentage}%</div>
                            </div>
                        )}

                        {/* Tombol Aksi */}
                        <div className="flex items-center justify-end">
                            <Link
                                href={route("plans.index")}
                                as="button"
                                type="button"
                                className="px-4 py-2 bg-gray-200 text-gray-800 rounded-md hover:bg-gray-300 mr-4"
                            >
                                Batal
                            </Link>
                            <button
                                type="submit"
                                disabled={processing}
                                className="bg-blue-500 text-white px-6 py-2 rounded disabled:bg-blue-300"
                            >
                                {processing
                                    ? "Menyimpan..."
                                    : plan
                                    ? "Perbarui"
                                    : "Simpan"}
                            </button>
                        </div>
                    </form>
                </div>

                {/* Kolom Cover (hanya tampil saat edit) */}
                {plan && (
                    <div className="bg-white p-6 rounded-lg shadow-md self-start">
                        <h2 className="text-xl font-semibold mb-4">
                            Cover Saat Ini
                        </h2>
                        {plan.cover ? (
                            <img
                                src={plan.cover}
                                alt="Cover"
                                className="w-full h-auto rounded mb-4"
                            />
                        ) : (
                            <div className="w-full h-48 bg-gray-200 flex items-center justify-center rounded mb-4">
                                <span className="text-gray-500">
                                    Tidak ada cover
                                </span>
                            </div>
                        )}
                    </div>
                )}
            </div>
        </div>
    );
}

// resources/js/pages/plans/Form.vue
<template>
    <AppLayout :title="formTitle">
        <template #header>
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                {{ formTitle }}
            </h2>
        </template>

        <div class="py-12">
            <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
                <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                    <div class="p-6 sm:px-20 bg-white border-b border-gray-200">
                        <form @submit.prevent="submit">
                            <!-- Title -->
                            <div class="mb-6">
                                <label
                                    for="title"
                                    class="block mb-2 text-sm font-medium text-gray-900"
                                >
                                    Judul Rencana
                                </label>
                                <input
                                    type="text"
                                    id="title"
                                    v-model="form.title"
                                    class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
                                    placeholder="Masukkan judul rencana..."
                                    required
                                />
                                <div
                                    v-if="form.errors.title"
                                    class="text-red-500 text-xs mt-1"
                                >
                                    {{ form.errors.title }}
                                </div>
                            </div>

                            <!-- Content -->
                            <div class="mb-6">
                                <label
                                    for="content"
                                    class="block mb-2 text-sm font-medium text-gray-900"
                                >
                                    Detail Rencana
                                </label>
                                <TrixEditor
                                    v-model="form.content"
                                    @trix-file-accept="handleFile"
                                    @trix-attachment-add="storeAttachment"
                                />
                                <div
                                    v-if="form.errors.content"
                                    class="text-red-500 text-xs mt-1"
                                >
                                    {{ form.errors.content }}
                                </div>
                            </div>

                            <!-- Cover Image -->
                            <div class="mb-6">
                                <label
                                    for="cover_image"
                                    class="block mb-2 text-sm font-medium text-gray-900"
                                >
                                    Gambar Sampul
                                </label>
                                <input
                                    type="file"
                                    @input="form.cover_image = $event.target.files[0]"
                                    class="block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 focus:outline-none"
                                    id="cover_image"
                                />
                                <progress
                                    v-if="form.progress"
                                    :value="form.progress.percentage"
                                    max="100"
                                >
                                    {{ form.progress.percentage }}%
                                </progress>
                                <div
                                    v-if="form.errors.cover_image"
                                    class="text-red-500 text-xs mt-1"
                                >
                                    {{ form.errors.cover_image }}
                                </div>
                                <img
                                    v-if="imageUrl && !form.cover_image"
                                    :src="imageUrl"
                                    class="mt-4 h-48 object-cover"
                                    alt="Current Cover"
                                />
                            </div>

                            <!-- Status (Selesai / Belum Selesai) -->
                            <div class="mb-6">
                                <label
                                    for="is_completed"
                                    class="block mb-2 text-sm font-medium text-gray-900"
                                >
                                    Status Rencana
                                </label>
                                <select
                                    id="is_completed"
                                    v-model.number="form.is_completed"
                                    class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
                                >
                                    <option :value="0">Belum selesai</option>
                                    <option :value="1">Selesai</option>
                                </select>
                                <div
                                    v-if="form.errors.is_completed"
                                    class="text-red-500 text-xs mt-1"
                                >
                                    {{ form.errors.is_completed }}
                                </div>
                            </div>

                            <!-- Submit Button -->
                            <div class="flex items-center justify-end">
                                <button
                                    type="submit"
                                    :disabled="form.processing"
                                    class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center"
                                    :class="{ 'opacity-25': form.processing }"
                                >
                                    {{
                                        isEditing
                                            ? "Perbarui Rencana"
                                            : "Simpan Rencana"
                                    }}
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </AppLayout>
</template>

<script setup>
import { computed } from "vue";
import { useForm } from "@inertiajs/vue3";
import AppLayout from "@/Layouts/AppLayout.vue";
import TrixEditor from "@/Components/TrixEditor.vue";
import axios from "axios";

const props = defineProps({
    plan: Object, // plan akan null jika 'create', dan berisi data jika 'edit'
});

const isEditing = computed(() => !!props.plan);
const formTitle = computed(() =>
    isEditing.value ? "Edit Rencana" : "Tambah Rencana Baru"
);
const imageUrl = computed(() =>
    props.plan && props.plan.cover ? `/storage/${props.plan.cover}` : null
);

const form = useForm({
    _method: isEditing.value ? "PUT" : "POST",
    title: props.plan?.title || "",
    content: props.plan?.content || "",
    cover_image: null,
    // gunakan 1/0 supaya gampang di-handle di Laravel
    is_completed: props.plan?.completed_at ? 1 : 0,
});

const submit = () => {
    const url = isEditing.value
        ? route("plans.update", props.plan.id)
        : route("plans.store");

    form.post(url, {
        // forceFormData: true, // gunakan ini jika ada masalah dengan pengiriman file
        onSuccess: () => form.reset("title", "content", "cover_image", "is_completed"),
    });
};

// Handler untuk Trix Editor
const handleFile = (e) => {
    // Mencegah file selain gambar untuk di-upload
    if (!e.file.type.match("image.*")) {
        e.preventDefault();
        alert("Hanya file gambar yang diizinkan.");
    }
};

const storeAttachment = (event) => {
    const attachment = event.attachment;
    const form_data = new FormData();
    form_data.append("attachment", attachment.file);

    axios
        .post(route("plans.attachments.store"), form_data, {
            headers: {
                "Content-Type": "multipart/form-data",
            },
            onUploadProgress: (progressEvent) => {
                attachment.setUploadProgress(
                    (progressEvent.loaded / progressEvent.total) * 100
                );
            },
        })
        .then((response) => {
            attachment.setAttributes({
                url: response.data.url,
                href: response.data.url,
            });
        })
        .catch((error) => {
            console.error("Upload failed:", error);
        });
};
</script>
